Online Course Portal_Web/Controllers/CourseBookingController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Course_Portal_DataAccess.Model.DTO;
using Online_Course_Portal_DataAccess.Model;
using Online_Course_Portal_Web.Service.IService;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Globalization;
using System.Security.AccessControl;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Online_Course_Portal_DataAccess.Model.ViewModel;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;
using Online_Course_Portal_DataAccess.Data;

namespace Online_Course_Portal_Web.Controllers
{
    public class CourseBookingController : Controller
    {
        private readonly ICourseBookingService _courseBookingService;
        private readonly ICourseService _courseService;
        private readonly IAdminService _adminService;
        private readonly IHttpContextAccessor _contextAccessor;
       
        
        
        public CourseBookingController(ICourseBookingService courseBookingService, ICourseService courseService,IHttpContextAccessor contextAccessor,IAdminService adminService)
        {

            _courseBookingService = courseBookingService;
            _courseService = courseService;
            _contextAccessor = contextAccessor;
            _adminService = adminService;
        }


        public async Task<IActionResult> Index()
        {
            var course = await _courseBookingService.GetAllAsync(_contextAccessor.HttpContext.Session.GetString("JWTToken"));
            
            var booking = _courseService.GetAllAsync(_contextAccessor.HttpContext.Session.GetString("JWTToken"));
           // var bokings = _adminService.GetAllApproveCourseAsync(_contextAccessor.HttpContext.Session.GetString("JWTToken"));
            ViewBag.booking = booking;


            return View(course);
        }
        
        public async Task<IActionResult> CreateBooking()
        {
            //var result = await _courseService.GetByIdAsync(id, HttpContext.Session.GetString("JWTToken"));

            //ViewData["a"] = result.AvailableSeats;
            //ViewData["b"] = result.courseName;
            //ViewData["c"] = result.EndDate.ToString("yyyy-MM-dd");

            //ViewData["d"] = result.StartDate.ToString("yyyy-MM-dd");
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> CreateBooking(CourseBooking course)
        //{
        //    //if (ModelState.IsValid)
        //    //{
        //        var result = await _courseBookingService.CreateCourseAsync(course);
        //        TempData["success"] = "Course Enrolled Successfully";
        //        return RedirectToAction(nameof(Index), new { id = result.Id });
        //   // }

        //    return View(course);
        //}

        [HttpPost]
        public async Task<IActionResult> CreateBooking(int courseId)
        {
            var course = await _courseService.GetByIdAsync(courseId, _contextAccessor.HttpContext.Session.GetString("JWTToken"));
            CourseBookingDTO booking = new CourseBookingDTO
            {
                CourseId = courseId,


            };


            await _courseBookingService.CreateCourseAsync(booking, _contextAccessor.HttpContext.Session.GetString("JWTToken"));
            TempData["Success"] = "Enrollment Done Successfully";
            return RedirectToAction(nameof(Index));



        }





        public async Task<IActionResult> DeleteCourseBooking(int id)
        {
            var course = await _courseBookingService.GetByIdAsync(id,_contextAccessor .HttpContext.Session.GetString("JWTToken"));
            return View(course);
        }

        [HttpPost]
        [ActionName("DeleteBooking")]
        public async Task<IActionResult> DeleteBooking(int id)
        {
            await _courseBookingService.DeleteCourseAsync(id, _contextAccessor.HttpContext.Session.GetString("JWTToken"));
            TempData["success"] = "Course UnEnrolled Successfully";

            return RedirectToAction(nameof(Index));
        }

    }
}

Online Course Portal_Web/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Online_Course_Portal_DataAccess.Model;
using Online_Course_Portal_DataAccess.Model.DTO;
using Online_Course_Portal_Web.Service.IService;
using System.Collections;
using System.Collections.Generic;
using System.Reflection.Metadata;

namespace Online_Course_Portal_Web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class CourseController : Controller
    {
        
        private readonly ICourseService _courseService;
        private readonly IHttpContextAccessor _contextAccessor;
        public CourseController(ICourseService courseService, IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
            _courseService = courseService;
        }


            public async Task<IActionResult> Index()
            {
                
                var posts = await _courseService.GetAllAsync(_contextAccessor.HttpContext.Session.GetString("JWTToken"));
                return View(posts);
            }
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreateDTO course)
        {
            if (ModelState.IsValid)
            {
                var result = await _courseService.CreateCourseAsync(course, HttpContext.Session.GetString("JWTToken"));
                TempData["success"] = "Course Created Successfully";
                return RedirectToAction(nameof(Index), new { id = result.Id });
            }

            return View(course);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var course = await _courseService.GetByIdAsync(id, HttpContext.Session.GetString("JWTToken"));
            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Course course)
        {
            if (ModelState.IsValid)
            {
                await _courseService.UpdateCourseAsync(id, course, HttpContext.Session.GetString("JWTToken"));
                TempData["success"] = "Course Updated Successfully";
                return RedirectToAction(nameof(Index), new { id });
            }

            return View(course);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var course = await _courseService.GetByIdAsync(id, HttpContext.Session.GetString("JWTToken"));
            return View(course);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteCourse(int id)
        {
            await _courseService.DeleteCourseAsync(id,HttpContext.Session.GetString("JWTToken"));
            TempData["success"] = "Course Deleted Successfully";
            return RedirectToAction(nameof(Index));
        }


    }
}

Online Course Portal_Web/Views/Shared/_CoursePartial.cshtml
@model Course

<tr>
<td>@Model.courseName</td>
<td>@Model.courseDescription</td>
<td>@Model.StartDate</td>
<td>@Model.EndDate</td>
<td>@Model.AvailableSeats</td>
</tr>

Online Course Portal_Web/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpaccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online_Course_Portal_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/Online_Course_Portal_Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_Course_Portal_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                                
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Course Status Page</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CourseBooking" asp-action="Index">CourseBooking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
           
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Online_Course_Portal_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Online Course Portal_Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success(' @TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success(' @TempData["error"]');
    </script>
}