Online Course Portal_Web/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Online_Course_Portal_DataAccess.Model;
using Online_Course_Portal_DataAccess.Model.DTO;
using Online_Course_Portal_Web.Service.IService;
using System.Collections;
using System.Collections.Generic;
using System.Reflection.Metadata;

namespace Online_Course_Portal_Web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class CourseController : Controller
    {
        
        private readonly ICourseService _courseService;
        private readonly IHttpContextAccessor _contextAccessor;
        public CourseController(ICourseService courseService, IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
            _courseService = courseService;
        }


            public async Task<IActionResult> Index()
            {
                
                var posts = await _courseService.GetAllAsync(_contextAccessor.HttpContext.Session.GetString("JWTToken"));
                return View(posts);
            }
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreateDTO course)
        {
            if (ModelState.IsValid)
            {
                var result = await _courseService.CreateCourseAsync(course, HttpContext.Session.GetString("JWTToken"));
                TempData["success"] = "Course Created Successfully";
                return RedirectToAction(nameof(Index), new { id = result.Id });
            }

            return View(course);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var course = await _courseService.GetByIdAsync(id, HttpContext.Session.GetString("JWTToken"));
            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Course course)
        {
            if (ModelState.IsValid)
            {
                await _courseService.UpdateCourseAsync(id, course, HttpContext.Session.GetString("JWTToken"));
                TempData["success"] = "Course Updated Successfully";
                return RedirectToAction(nameof(Index), new { id });
            }

            return View(course);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var course = await _courseService.GetByIdAsync(id, HttpContext.Session.GetString("JWTToken"));
            return View(course);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteCourse(int id)
        {
            await _courseService.DeleteCourseAsync(id,HttpContext.Session.GetString("JWTToken"));
            TempData["success"] = "Course Deleted Successfully";
            return RedirectToAction(nameof(Index));
        }


    }
}

Online Course Portal_Web/ViewComponents/CountDownViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Common;
using Online_Course_Portal_DataAccess.Model;
using Online_Course_Portal_DataAccess;
using Online_Course_Portal_Web.Service.IService;

namespace Online_Course_Portal_Web.ViewComponents
{
    public class CountDownViewComponent : ViewComponent
    {
        private readonly ICourseService _courseService;


        public CountDownViewComponent(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            string token = HttpContext.Session.GetString("JWTToken");

            var courses = await _courseService.GetAllAsync(token);


          //  IEnumerable<Course> model = JsonConvert.DeserializeObject<List<Course>>(Convert.ToString(courses));




            Course firstEvent = courses.OrderBy(e => e.StartDate).FirstOrDefault();

            if (firstEvent != null)
            {
                var countdownTime = DateTime.UtcNow - firstEvent.StartDate;

                return View("Default", countdownTime);
            }

            return Content("No courses found.");
        }

    }
}

Online Course Portal_Web/Views/Course/Create.cshtml
@model Course

<h1>Create Course</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post" asp-action="Create">
            <div class="form-group">
                <label asp-for="courseName"></label>
                <input asp-for="courseName" class="form-control" />
                <span asp-validation-for="courseName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="courseDescription"></label>
                <textarea asp-for="courseDescription" class="form-control"></textarea>
                <span asp-validation-for="courseDescription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="StartDate"></label>
                <input asp-for="StartDate" type="date" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EndDate"></label>
                <input asp-for="EndDate" type="date" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AvailableSeats"></label>
                <input asp-for="AvailableSeats" type="number" class="form-control" />
                <span asp-validation-for="AvailableSeats" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Create Course</button>
            <a asp-controller="Course" asp-action="Index" class="btn btn-secondary">Back to List</a>
        </form>
    </div>
</div>

Online Course Portal_Web/Views/Course/Delete.cshtml
@model Course


<h1>Delete Course</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post" asp-action="Delete">
            <div class="form-group">
                <label asp-for="courseName"></label>
                <input asp-for="courseName" class="form-control" readonly />
            </div>

            <div class="form-group">
                <label asp-for="courseDescription"></label>
                <textarea asp-for="courseDescription" class="form-control" readonly></textarea>
            </div>

            <div class="form-group">
                <label asp-for="StartDate"></label>
                <input asp-for="StartDate" type="date" class="form-control" readonly />
            </div>

            <div class="form-group">
                <label asp-for="EndDate"></label>
                <input asp-for="EndDate" type="date" class="form-control" readonly />
            </div>

            <div class="form-group">
                <label asp-for="AvailableSeats"></label>
                <input asp-for="AvailableSeats" type="number" class="form-control" readonly />
            </div>

            <input type="hidden" asp-for="Id" />

            <button type="submit" class="btn btn-danger">Delete</button>
            <a asp-controller="Course"  asp-action="Index" class="btn btn-secondary">Back to List</a>
        </form>
    </div>
</div>

Online Course Portal_Web/Views/Course/Edit.cshtml
@model Course


<h1>Edit Course</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post" asp-action="Edit" >
            <div class="form-group">
                <label asp-for="courseName"></label>
                <input asp-for="courseName" class="form-control" />
                <span asp-validation-for="courseName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="courseDescription"></label>
                <textarea asp-for="courseDescription" class="form-control"></textarea>
                <span asp-validation-for="courseDescription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="StartDate"></label>
                <input asp-for="StartDate" type="date" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EndDate"></label>
                <input asp-for="EndDate" type="date" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AvailableSeats"></label>
                <input asp-for="AvailableSeats" type="number" class="form-control" />
                <span asp-validation-for="AvailableSeats" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="Id" />

            <button type="submit" class="btn btn-primary">Edit</button>
            <a   asp-controller="Course" asp-action="Index" class="btn btn-secondary">Back to List</a>
        </form>
    </div>
</div>

Online Course Portal_Web/Views/Course/Index.cshtml
@model IEnumerable<Course>
@using Online_Course_Portal_Web.Models
@using Online_Course_Portal_DataAccess.Model



<h2>Courses</h2>
<div class="col text-end pt-1">
    <a asp-controller="Course" asp-action="Create" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i>Create Course</a>
</div>

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Course Name</th>
                <th>Course Description</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>AvailableSeats</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var result in Model)
            {

                Html.RenderPartial("_CoursePartial", result);

               <tr>
                <td>
                <a asp-action="Edit" asp-route-id="@result.Id">Edit</a>
                <a asp-action="Delete" asp-route-id="@result.Id">Delete</a>
                </td>
               </tr>
                
                
                
                @*<tr>*@
                    @*<td>@result.courseName</td>
                    <td>@result.courseDescription</td>
                    <td>@result.StartDate</td>
                    <td>@result.EndDate</td>
                    <td>@result.AvailableSeats</td>
                    Html.RenderPartial("_CoursePartial",result);*@

                    @*<td>
                        <a asp-action="Edit" asp-route-id="@result.Id">Edit</a> 
                        <a asp-action="Delete" asp-route-id="@result.Id">Delete</a>
                    </td>
                </tr>*@
            }
        </tbody>
    </table>
    @await Component.InvokeAsync("CountDown")
}
else
{
    <p>No Course available.</p>
}